#' Generic plot function for crosnma.model object.
#'
#' @param x The object generated by the crosnma.run function.
#'
#' @param ... \dots
#'
#' @export
#'
plot.crosnma <- function(x, ...)
{
  plot(x$samples, ...)
}
