#' Generic summary function for crosnma.run object
#' @param x The object generated by the crosnma.run function.
#'
#' @param digits The number of significant digits printed. The default value is 3.
#'
#' @param quantiles A numeric vector of probabilities with values in [0,1]. The default value is
#'                  intervals = c(0.025, 0.5, 0.975).
#'
#' @param ... \dots
#'
#' @export
#'
summary.crosnma <- function(x, digits = 3,  quantiles = c(0.025, 0.5, 0.975), expo=TRUE, ...)
{

  # initial
  sum.fit <-summary((x$samples),digits=digits,quantiles = quantiles, ...)
  # mean and sd
  sum.fit.mat <- sum.fit$statistics[,c('Mean','SD')]
  # add quantiles
  sum.fit.mat <- cbind(sum.fit.mat, sum.fit$quantiles)
 if (expo) {sum.fit.mat <- exp(sum.fit.mat) }
  # add Rhat
  Rhat <- round(rhat(x$samples)$psrf[,'Point est.'],3)
  sum.fit.mat <- cbind(sum.fit.mat,Rhat)

  # add number of effective sample size
  n.eff <- round(effectiveSize(x$samples))
  sum.fit.mat <- cbind(sum.fit.mat,n.eff)


  # attach treatment names to d's
  row.names(sum.fit.mat)[startsWith(rownames(sum.fit.mat),"d")] <- paste("d",c(x$trt.key$trt.ini),sep=".")
  return(sum.fit.mat)
}
